version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    ports:
      - 5632:5432

  production:
    container_name: production
    build:
      context: .
      target: production